# Generated by Django 5.1.15 on 2026-01-15 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('preparing', 'Preparing'), ('done', 'Done')], max_length=20)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tables.table')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
