# Generated by Django 5.1.15 on 2026-01-26 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='dinning_session',
            new_name='dinningSession',
        ),
    ]
