# Generated by Django 5.1.15 on 2026-01-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='total',
            new_name='subtotal',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('preparing', 'Preparing'), ('done', 'Done')], default='pending', max_length=20),
        ),
    ]
